[project]
name = "musicnn"
version = "0.1.0"
description = "musicnn optimization"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "librosa>=0.11.0",
    "matplotlib>=3.10.9",
    "pandas>=2.3.3",
    "pydot>=4.0.1",
    "pyqt6>=6.11.0",
    "tensorflow-io==0.36.*",
    "tensorflow-model-optimization>=0.8.1",
    "tensorflow[and-cuda]==2.16.*",
]
